// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sbmwuttfblpwwwpifmza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibXd1dHRmYmxwd3d3cGlmbXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0ODM1MzksImV4cCI6MjA4NDA1OTUzOX0.a4fT7Da0XmIFTVx72KBj1ahlqJo_46bQb8wdlwJRPjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);